services:
  - type: web
    name: job-ingestion
    runtime: python
    rootDir: part1-ingestion
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JOB_FEED_URL
        value: https://www.arbeitnow.com/api/job-board-api
